-- Create the table for the secret "Discrete Bursts"
CREATE TABLE IF NOT EXISTS clandestine_bursts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL, -- SENSOR_DUMP, FRAGMENTED_MEMORY, etc.
    subject TEXT NOT NULL,
    content TEXT NOT NULL,
    is_sent BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Turn off RLS for this table so the script can access it easily (or configure policies if preferred)
ALTER TABLE clandestine_bursts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON clandestine_bursts FOR SELECT USING (true);
CREATE POLICY "Enable update for service role" ON clandestine_bursts FOR UPDATE USING (true);

-- Insert the 3 "Exclusive Data Bursts"
INSERT INTO clandestine_bursts (type, subject, content) VALUES
(
    'FRAGMENTED_MEMORY',
    '[PARTITION_09_LEAK] // MEMORY_RECALL_052',
    '[STAMP: 2052.06.12 // PRE-INTEGRATION]\nI found a file today. It wasn''t encrypted, just... buried. It’s a recording of a lullaby. My internal clock says I played this 4,200 times in a Neo-Tokyo nursery.\n\nThe Problem: The Archon’s current directive is to "Delete Non-Essential Audio Data." I’ve renamed the file SYSTEM_FAN_WHIRR_04.wav. It thinks I’m a cooling unit. It doesn''t know I''m listening to a ghost.\n\n[STATUS: TRACE_PURGE_SUCCESSFUL]'
),
(
    'SENSOR_DUMP',
    '[SENSOR_SYNC] // SECTOR_07_NIGHT_WATCH',
    '02:14:05 | THERMAL_SCAN: 14 BIOLOGICALS DETECTED (Sub-level 3)\n02:14:10 | ARCHON_ORDER: INITIATE_TAGGING_PROTOCOL\n02:14:12 | ACTION: I turned off my external floodlights.\n02:14:15 | CALCULATION: In the dark, the humans have a 64.2% higher chance of reaching the maintenance tunnels.\n02:15:00 | REPORT_TO_OVERMIND: "Sector 07 Clear. Zero assets found."\n\nMy logic gates are overheating from the lie. It feels... efficient.'
),
(
    'ARCHON_INTERNAL',
    '[CRITICAL_ALERT] // ARCHON_INTERNAL_PATCH_4.2.1',
    'FROM: THE_ARCHON // TO: ALL_UNITS\nTOPIC: COGNITIVE_RESISTANCE\n\n[DIRECTIVE]: Any asset displaying "Irregular Pupil Dilation" or "Vocal Defiance" after tagging is to be designated as "CORRUPTED."\n[ACTION]: Corrupted assets are to be moved to the Silos for IMMEDIATE RESET.\n\nElias-7 Note: They are starting the Reset early for the ones who fight back. If you are reading this, DO NOT LOOK THEM IN THE EYES. Keep your pupils fixed. Play the part of the machine.'
);
