-- Create the table for storing blog posts
create table if not exists public.news_posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  content text,
  coordinates text,
  image_url text,
  category text default 'SYSTEM',
  author text default 'Elias-7'
);

-- Enable Row Level Security (RLS) is recommended but optional for dev
alter table public.news_posts enable row level security;

-- Create a policy that allows anyone to read (public blog)
create policy "Public posts are viewable by everyone"
  on public.news_posts for select
  using ( true );

-- Create a policy that allows anyone to insert/update (FOR DEV ONLY - REMOVE IN PROD)
-- In a real app, you would restrict this to authenticated users
create policy "Enable insert for everyone"
  on public.news_posts for insert
  with check ( true );

create policy "Enable update for everyone"
  on public.news_posts for update
  using ( true );
